### PR TITLE
visjs replaced with custom builded version, fixed loading in producti…

### PR DESCRIPTION
**Pull request by boajer**
…on mode

### CODE REVIEW

**Comment by ssipasseuth** [comment]
hi, where can I get a good sample tree I can use to test this ?

**Comment by ssipasseuth** [comment]
The second commit has nothing to do with fixing the issue on the minified version. I would consider making another PR next time.

**Comment by boajer** [comment]
Hi @ssipasseuth , i have send you email with trees attached.
Regarding second commit you are absolutely right, it was accidentally pushed in this branch

**Comment by ssipasseuth** [comment]
Thanks I tested the samples and they import correctly. However I am not sure if the visualization is expected.  Are you still working on improving the rendering or is it the final version ? Is it extpected that we can only move nodes horizontally. On top of that, the largest sample renders not so well.
view_tree

**Pull request merged**
